#!/usr/bin/env python3

'''
Count the nubmer of Sequence Types from MLST output generated by mlst tool (https://github.com/tseemann/mlst)
usage:
python3 count_ST.py <MLST_output>
'''
import sys

data_dict = {}
with open(sys.argv[1], 'r') as fh:
	for line in fh:
		line = line.strip().split()
		data_dict[line[2]] = data_dict.get(line[2], 0) + 1


for i in sorted(data_dict.keys()):
	'''only print ST with >= 10 genomes'''
	if data_dict[i] >= 10:
		print(f'{i}\t{data_dict[i]}')
